### ISSUE TITLE
Figure out a mechanism to add telemetry information for browser clients

### ISSUE THREAD

**Issue by amarzavery** [Azure/ms-rest-js#228]
Currently we put package information in the user-agent header  for clients that run in the node.js runtime. However, in browser land, one cannot touch the user-agent header. It is forbidden to do so.

Hence we need to come up with a different mechanism to inject package name and version for telemetry.

/cc @RikkiGibson @kirthik  @JasonRShaver @salameer

**Comment by kpajdzik** [comment]
> Had a short syncup with Jason on Friday. We have agreed to use x-ms-command-name  and x-ms-parameter-name request headers for sending telemetry for browser clients. We will be using the standard user-agent header for node.js clients. In this way it is easy to distinguish usage of browser and node.js sdks.

**Comment by seiffs** [comment]
Could you please advise how to disable sending the telemetry headers? After upgrade from ms-rest-js to @azure/ms-rest-js there is now this new x-ms-command-name header and I can't find any way how to remove it. Unfortunatelly our API GW has very strict header rules, so all the request now fail on the preflight OPTIONS request because of this extra header.

**Comment by kpajdzik** [comment]
@seiffs You need to replace default UserAgent policy with an instance created by you ([code](https://github.com/Azure/ms-rest-js/blob/master/lib/policies/userAgentPolicy.ts#L36)) or remove it from already created default policies.
