### ISSUE TITLE
Options-specified requestPolicyFactories removes all defaults

### ISSUE THREAD

**Issue by stevegreatrex** [Azure/ms-rest-js#309]
**Package Version**: 1.2.6
- [x] **browser**
    - **name/version**: Chrome 71.0.3578.98

**Describe the bug**
When you specify `requestPolicyFactories` in the options to `ServiceClient` it does not create the default policies.  This looks like it would significantly change the behaviour; in my specific case I observed that it no longer parses body content.

This means that it is not possible to append a single new policy via the options.

I'm not sure if this is technically a bug because the expected behaviour of `requestPolicyFactories` is not documented (that I have seen, at least!).  My expectation was that this would work similarly to how `filters` could be used in earlier versions of `ms-rest-js` so it seemed like "broken" behaviour to me, but you could make an argument that this is a feature request as well 😄

See [serviceClient.ts](https://github.com/Azure/ms-rest-js/blob/afdad404784a989011912dc6df720b6e494a0c04/lib/serviceClient.ts#L126) for the line that selects either the options-specified version or creates the defaults

**To Reproduce**
1. Instantiate `ServiceClient` with the following options:
```typescript
{
  requestPolicyFactories: [customPolicy()]
}
```
2. Make a request via `client.sendRequest` that should receive a JSON payload
3. Observe that `response.parsedBody` is undefined and only `response.bodyAsText` is populated

**Expected behavior**
I would expect to have some way to modify the final list of policies.  For example, I may want to append a policy or to insert a new policy at the start of the pipeline.

I'm not sure what the best solution would be but I guess that something like the following would be most flexible:

```typescript
{
  configurePolicyFactories: (defaultPolicyFactories: RequestPolicyFactory[]) => 
    [
      customPolicy1(), 
      ...defaultPolicyFactories,
      customPolicy2()
    ]
}
```

I'm not whether this would work better alongside or in place of the existing `requestPolicyFactories` option though!

**Comment by daschult** [comment]
Hi @stevegreatrex. We can definitely understand your confusion over this issue, because we went back and forth internally while implementing this about what the correct behavior should be. We ended up going with this implementation as an attempt to not provide any "magic" to users.
You're absolutely right. If you provide a value for the `requestPolicyFactories` property, we won't add the default factories. The intention here was that we didn't want to break applications that create custom requestPolicy pipelines (such as you are doing). If you appended (or pre-pended) a custom request policy to the default request policy pipeline, then it's possible we might add new default request policies in the future that may interfere with your custom policy. Rather than having customers depend on our default behavior remaining immutable, we decided that if customers want to modify the request policy pipeline/factories, then they need to own the entire pipeline.
Your idea about providing a function that takes the `defaultPolicyFactories` as an argument is a good idea, but it too runs into the same problem that we're trying to avoid, which is to prevent breaking customers through future changes.
Feel free to disagree. We're open to extending this to make your life better/easier, but understand that we're really trying to keep things safer in the long run.

**Comment by stevegreatrex** [comment]
Hi @daschult, thanks for the detailed response.

I can see why you would want to avoid breaking future customer changes.  The counter argument is that omitting a policy could easily be as breaking as including an unexpected one 😄

Seeing as you have already released the version that you have then I think that adding another option for (effectively) the same thing is just going to cause confusion.

How about we go for an opt-in approach instead?  If there were a `ServiceClient.createDefaultPipeline()` or similar then consumers could do something like the below?

```typescript
new ServiceClient({
  requestPipelineFactories: [
    customPolicy(),
    ...ServiceClient.createDefaultPipeline(),
  ]
});
```

What do you think?  This has the added benefit of being really easy to implement!
