### ISSUE TITLE
SendOperationRequest doesn't set "Accept" header

### ISSUE THREAD

**Issue by joheredi** [Azure/ms-rest-js#395]
The "Accept" header is never set in ms-rest-js this causes issues such as #7869 in which some services may send something different by default if the Accept header is not set.

For example in the bug mentioned above, JSON is assumed, however the default service default behavior is to send XML.

A workaround for this issue has been to send the Accept header with each operation, however we should be able to set the right header in ms-rest-js based on the information in the OperationSpec

Workaround sample
```typescript
const result = client.listEntities(
  query, 
  { customHeaders: { accept: "application/json" } }
);
```

**Comment by ramya-rao-a** [comment]
This would require a change in the code generator as well as a change to this package.

Since the accept value can also different between operations, the code generator would need to add a property in the OperationSpec interface to hold the Accept header value. `@azure/ms-rest-js` would then need to read this value and adding the header in sendOperationRequest.

This change would affect all future re-generated code.

But, as discussed in https://github.com/Azure/azure-sdk-for-js/issues/10141, there are better ways to do this in the latest version of the code generator that is currently in development.

So, to reduce risk and churn, the recommendation is to tweak the auto-generated code manually and update the sendRequest() method in the client to add the right header.

This won't work for services that have different accept headers for each operation. But, since we havent seen any such cases, we will be sticking to the above recommendation.

https://github.com/Azure/azure-sdk-for-js/issues/10141 and https://github.com/Azure/autorest.modelerfour/issues/324 will be used to track further work here
